spring:
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.PostgreSQLDialect
#      generate-ddl: true
#      defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath*:schema.sql

logging:
  level:
    org:
      springframework:
        security: debug

jwt:
  secretKey: hellworldjwt
  token:
      expiredAt: 2592000000

#  servlet:
#    # ?? ??? ??? ??
#    multipart:
#      max-file-size: 1024MB
#      max-request-size: 1024MB

---
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org:
      springframework:
        security: debug

#  servlet:
#    # ?? ??? ??? ??
#    multipart:
#      max-file-size: 1024MB
#      max-request-size: 1024MB

---

spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      springframework:
        security: debug

#  servlet:
#    # ?? ??? ??? ??
#    multipart:
#      max-file-size: 1024MB
#      max-request-size: 1024MB
