logging:
  level:
    org:
      springframework:
        security: debug

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.PostgreSQLDialect
      generate-ddl: true
      defer-datasource-initialization: true

    open-in-view: false
  sql:
    init:
      mode: always
      schema-locations: classpath*:schema.sql


#  servlet:
#    # 파일 업로드 사이즈 제한
#    multipart:
#      max-file-size: 1024MB
#      max-request-size: 1024MB





