logging:
  level:
    org:
      springframework:
        security: debug

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.PostgreSQLDialect

#  servlet:
#    # ?? ??? ??? ??
#    multipart:
#      max-file-size: 1024MB
#      max-request-size: 1024MB





